#!/bin/sh
# Executed by startx (run your window manager from here)

# Make sure this is before the 'exec' command or it won't be sourced.
~/.config/x11/xprofile &

# Merge in defaults and keymaps
xrandr --dpi 96 &
xrdb ~/.config/x11/xresources &
setxkbmap -layout us -option ctrl:nocaps &
xset r rate 200 40 &
# setxkbmap -layout us,ara -option grp:win_space_toggle,caps:escape &

# Start some nice programs
unclutter &
xwallpaper --center "$XDG_DATA_HOME"/backgrounds/2021-08-11-13-17-47-fallen_angel_face.jpg &
# picom --config ~/.config/picom/picom.conf --experimental-backend -b &
# dunst &
# picom &

# Setup audio
/usr/bin/pipewire &
/usr/bin/pipewire-alsa &
/usr/bin/pipewire-pulse &
/usr/bin/pipwerire-jack &
/usr/bin/wireplumber &

# Update exchange rates
qalc -exrates >/dev/null &

exec herbstluftwm --locked
