[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[templates]
defer = { value = 'zsh-defer source "{{ file }}"', each = true }

[plugins.zabb]
github = "Mellbourn/zabb"
use = ["{{ name }}.plugin.zsh"]
apply = ["defer"]

[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]
apply = ["defer"]

[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"
apply = ["defer"]
use = ["{{ name }}.plugin.zsh"]

[plugins.zsh-vi-mode]
github = "jeffreytse/zsh-vi-mode"
use = ["{{ name }}.plugin.zsh"]
